name: build nbconvert_html5 and export samples

on: 
  push:
    branches-ignore:
      - gh-pages
    paths:
      - nbconvert_html5/**
      - "pyproject.toml"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
        name: Fetch all history for all tags and branches
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install hatch
      - name: Convert
        run: |
          python -m hatch run task:convert
      - name: Build the docs
        run: |
          python -m hatch run docs:build
      - name: Deploy main 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.ref_name == 'main' }}
        with:
          folder: site # The folder the action should deploy.
          single-commit: true
      - name: Deploy non-main 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.ref_name != 'main' }}
        with:
          folder: site # The folder the action should deploy.
          single-commit: true
          target-folder: branch/${{ github.ref_name }}        