
name: pre release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    - name: Test the project  
      run: hatch run test:run
    - name: Build
      run: hatch build
    - name: Publish package
      run: hatch publish -r test --user ${{secrets.HATCH_INDEX_USER}} --auth ${{secrets.HATCH_TEST_INDEX_AUTH}}
      if: github.event_name != 'release'
    - name: Test the released packaged
      run: hatch run release:test
      if: github.event_name != 'release'